@MinimaApiRest_HostAddress = http://localhost:5174

POST  {{MinimaApiRest_HostAddress}}/createrUser/
Accept: application/json

###


POST {{MinimaApiRest_HostAddress}}/beer/
Accept: application/json
Content-Type: application/json

{
    "name": "Isaac Jtm"
}